language: generic

sudo: required

# Only run test when committing to a master branch.
branches:
  only:
    - master

env:
  globaL:
    - COMPOSE_HTTP_TIMEOUT=3600

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:
  # upgrade docker-engine to specific version
  - git clone http://github.com/aegir-project/tests.git
  - cd tests
  - sudo bash travis/prepare-docker.sh

  - sudo mkdir vendor
  - sudo chmod 777 vendor

  - sudo mkdir bin
  - sudo chmod 777 bin

  - cd ..
  - sudo docker build --rm -t aegir/hostmaster:local .

script:
  # The test run is included in the docker-entrypoint-tests.sh file.
  - cd tests/travis
  - sg - docker -c 'docker-compose run hostmaster --rm'
