version: '2'

services:

  hostmaster:
    image: aegir
    ports:
      - 12345:80
    hostname: aegir.docker
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword