version: '2'

services:

  hostmaster:
    image: aegir/hostmaster
    ports:
      - 80:80
    hostname: aegir.docker
    links:
      - database
    depends_on:
      - database
    environment:
      VIRTUAL_HOST: aegir.docker
      MYSQL_ROOT_PASSWORD: strongpassword

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword